name: CI

on:
  pull_request:
    branches: 
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Set environment variables
        run: |
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV
          echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" >> $GITHUB_ENV
          echo "PORT=${{ secrets.PORT }}" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run builds
        run: npm run client:build && npm run server:build

      - name: Run tests
        run: npm test

      merge:
        runs-on: ubuntu-latest
        needs: tests
    
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
    
          - name: Merge pull request
            run: gh pr merge ${{ github.event.pull_request.number }} --merge